### ISSUE TITLE
How could I set the number of classes for the model?

### ISSUE THREAD

**Issue by HeroadZ** [ohmeow/blurr#13]
Hello, thank you for this excellent work!
I'm a beginner of fastai and huggingface.

And I'm now using your library for sequence classfication problem with more than 2 classes.
I think it's necessary to set the number of class for huggingface. (Cause imdb is running correctly while mine cannot.)
But I don't know how according to your docs.
Could you give me some suggestions?

**Comment by HeroadZ** [comment]
I'm now using a very ugly way 😢  please help me
```python
hf_arch, hf_config, hf_tokenizer, hf_model = BLURR_MODEL_HELPER.get_hf_objects(
    pretrained_model_name,  task=task
)
hf_config.num_labels = num_labels
hf_arch, hf_config, hf_tokenizer, hf_model = BLURR_MODEL_HELPER.get_hf_objects(
    pretrained_model_name,  task=task, config=hf_config
)
```

**Comment by ohmeow** [comment]
Its not that ugly ... but no reason to call `get_hf_objects` twice :).

Checkout out the docs [here](https://ohmeow.github.io/blurr/modeling-core/), in particular the multi-label example.  You'll see something like this which is a bit more efficient:

```
task = HF_TASKS_AUTO.SequenceClassification

pretrained_model_name = "roberta-base" # "distilbert-base-uncased" "bert-base-uncased"
config = AutoConfig.from_pretrained(pretrained_model_name)
config.num_labels = len(lbl_cols)

hf_arch, hf_config, hf_tokenizer, hf_model = BLURR_MODEL_HELPER.get_hf_objects(pretrained_model_name, 
                                                                               task=task, 
                                                                               config=config)

**Comment by HeroadZ** [comment]
Thanks a lot! That's faster and simpler.
