### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by vishnureddys** [ohmeow/blurr#14]
When I run `pip install ohmeow-blurr`, most of the packages are installed but I get this error at the bottom. Is there something wrong with the dependencies or am I doing it wrong?  

`ERROR: Could not find a version that satisfies the requirement torch>=1.6.0 (from fastai>=2.0.0->ohmeow-blurr) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)  
ERROR: No matching distribution found for torch>=1.6.0 (from fastai>=2.0.0->ohmeow-blurr)`

**Comment by vishnureddys** [comment]
I installed fastai as well and I am still getting this error. Any idea if I'm doing something wrong with my installation?

**Comment by ohmeow** [comment]
fastai requires pytorch >= 1.6 ... and from the error, it looks like it can't find it on your system.

**Comment by vishnureddys** [comment]
Thank you, it seems to work now.
