### ISSUE TITLE
Windows issue 

### ISSUE THREAD

**Issue by henry090** [ohmeow/blurr#18]
Hi. Is there a way to fix this?

```
Collecting git+https://github.com/ohmeow/blurr.git
  Cloning https://github.com/ohmeow/blurr.git to c:\users\runner~1\appdata\local\temp\pip-req-build-gaye0t66
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-req-build-gaye0t66\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-req-build-gaye0t66\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\RUNNER~1\AppData\Local\Temp\pip-pip-egg-info-mpwpr2p4'
         cwd: C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-gaye0t66\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-gaye0t66\setup.py", line 42, in <module>
        long_description = open('README.md').read(),
      File "C:\Users\RUNNER~1\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13891: character maps to <undefined>
```
__Github Actions__: https://github.com/henry090/fastai/pull/58/checks?check_run_id=1367643542

**Comment by ohmeow** [comment]
Sorry but I currently don't support Windows (only Linux).

With that said, if you want to submit any PRs to make this Windows friendly
I'm all ears ... I just don't have the time to invest in it myself.

Thanks - wg

**Comment by EinAeffchen** [comment]
To be able to install on windows simply comment out these two lines in the setup.py:

    #long_description = open('README.md').read(),
    #long_description_content_type = 'text/markdown',

The README is what cuases the charmap error on windows.

**Comment by ohmeow** [comment]
Thanks for this.

Any way I can update the setup.py so you all don't have to comment that section out?  Glad to update it to make it easier for Windows folks to install the lib.  Lmk.

**Comment by EinAeffchen** [comment]
The better fix than commenting it out would probably be to add the encoding:
`    long_description = open('README.md', encoding='utf-8').read(),`
`    long_description_content_type = 'text/markdown',`
If this also works on linux that is

**Comment by ohmeow** [comment]
Just pushed a new release ... if you get a chance, can you try installing
the library and windows and lmk if all is kosher now?

Thanks - wg

**Comment by EinAeffchen** [comment]
Works great, thanks!
