### ISSUE TITLE
A suggestion about HF_Splitter

### ISSUE THREAD

**Issue by tianjianjiang** [ohmeow/blurr#20]
Hi,

First let me express my gratitude to your great work! Without it, I can't run my experiments easily.

I suppose you know that already, since HF 3.3.0, the pooling layer is removed from classification models, so for parameter groups, it becomes 3 instead of 4, which can make discriminative fine-tuning and gradual unfreezing less effective. The situation makes me wonder, perhaps HF_Splitter can have an option (or by default) that further split encoder block of Transformer layer by layer?

Thank you!

**Comment by ohmeow** [comment]
Thanks for the kind words! I'm glad the library has been helpful for you.

re: splitting you can customize this however you want pretty easily.  If
you want to split it up further that should be pretty easy, just look at
the source for `hf_splitter` and define your splitting function based on
that.  `hf_splitter` relies on conventions in the huggingface library that
works well generally ... but it by no means its going to work well in all
cases or is even the best in any case.  For example, in the summarization
code we implement an entirely different splitting strategy based on
architecture that works much better than the default.

If you get a chance to experiment with different splitting strategies and
they end up working better, let me know.

Thanks - wg

**Comment by tianjianjiang** [comment]
Hi,

Yes, I understand that splitting strategy depends on the downstream task. 👍
My original thought was merely about what if 3 groups by default won't help in any situation at all.
However, your reply is actually quite helpful to me because I didn't notice the different usage of the summarization example.
Thank you!

Mike
