### ISSUE TITLE
Unexpected behavior of freeze()?

### ISSUE THREAD

**Issue by YipingNUS** [ohmeow/blurr#23]
Hi, thanks for providing the library. It works like a charm.

There's one potential issue I noticed regarding the freeze() method. What I observed it that it freezes until the **second last encoder layer**. I'm using seq2seq distilbart model. It's a bit blur what fast.ai docstring "Freeze up to last parameter group" means when we have nested layers. But I was expecting it should freeze up to the second last decoder layer or up to before the decoder if it as a whole is counted as a parameter group.

Is the current behavior by design? 

To reproduce the finding

```
pretrained_model_name = "sshleifer/distilbart-cnn-6-6"
hf_arch, hf_config, hf_tokenizer, hf_model = BLURR_MODEL_HELPER.get_hf_objects(pretrained_model_name, model_cls=BartForConditionalGeneration)
```
```
text_gen_kwargs = { **hf_config.task_specific_params['summarization'], **{'max_length': 32, 'min_length': 8} }
model = HF_BaseModelWrapper(hf_model)
model_cb = HF_SummarizationModelCallback(text_gen_kwargs=text_gen_kwargs)

learn = Learner(dls, 
                model,
                opt_func=ranger,
                loss_func=CrossEntropyLossFlat(),
                cbs=[model_cb],
                splitter=partial(summarization_splitter, arch=hf_arch)).to_fp16()

learn.create_opt() 
learn.freeze()
```
then
```
count = 0
for parameter in learn.model.hf_model.model.decoder.parameters():  # change decoder to encoder, shared
    if parameter.requires_grad:
        count += 1
print(count)
```
It shows that there're 158 trainable decoder parameters, 26 encoder parameters and 0 shared (embedding) parameters.

**Comment by ohmeow** [comment]
Yah, see the [seq2seq_splitter](https://github.com/ohmeow/blurr/blob/master/blurr/modeling/seq2seq/core.py#L152) function for how the parameter groups are created for the seq2seq models.

I'm following, in general, what I've found in the huggingface repo or have found to work best in my use cases.  That of course doesn't mean they're the best defaults or the best defaults in all cases :).  Having said that, you could define your own splitter method and make it work however you like.  I've seen some folks even go so far as to create a different parameter group for *each* layer in the encoder and decoder layers.

Anyways, if you come up with something better, let me know. 

Thanks!

**Comment by waisyousofi** [comment]
> Yah, see the [seq2seq_splitter](https://github.com/ohmeow/blurr/blob/master/blurr/modeling/seq2seq/core.py#L152) function for how the parameter groups are created for the seq2seq models.
> 
> I'm following, in general, what I've found in the huggingface repo or have found to work best in my use cases. That of course doesn't mean they're the best defaults or the best defaults in all cases :). Having said that, you could define your own splitter method and make it work however you like. I've seen some folks even go so far as to create a different parameter group for _each_ layer in the encoder and decoder layers.
> 
> Anyways, if you come up with something better, let me know.
> 
> Thanks!


thanks for this cool helper lib.

can you tell why do we need splitter?
