### ISSUE TITLE
'NoneType' object has no attribute 'clone'

### ISSUE THREAD

**Issue by abedkhooli** [ohmeow/blurr#24]
Using the latest `! pip install -q ohmeow-blurr` and getting the above error. Is there an issue with Fastai?
```
----> 1 learn.fit_one_cycle(1, lr_max=3e-3) 
...
/usr/local/lib/python3.6/dist-packages/fastai/learner.py in _do_one_batch(self)` 
  171         if len(self.yb):
    172             self.loss_grad = self.loss_func(self.pred, *self.yb)
--> 173             self.loss = self.loss_grad.clone()
    174         self('after_loss')
    175         if not self.training or not len(self.yb): return

AttributeError: 'NoneType' object has no attribute 'clone'
```

**Comment by ohmeow** [comment]
Yup. An issue with the latest version of fastai and how it handles the loss function.

Working on a fix now; will post here when its checked in. Thanks!

**Comment by ohmeow** [comment]
This should be fixed now with the latest release.  Try it out and feel free to close out the ticked if all works.

Thanks again -wg
