### ISSUE TITLE
fine-tune bart with custom dataset in other language?

### ISSUE THREAD

**Issue by HeroadZ** [ohmeow/blurr#25]
Thanks for this great work! 
I found your example on how to fine-tune Bart with CNN/DM dataset. It's very helpful.
Is it possible to fine-tune Bart with the dataset in another language?
If possible, I think it is necessary to train a SentencePiece tokenizer with a Japanese corpus.
Do you have any advice?

**Comment by ohmeow** [comment]
I would take a look at using mBART ... see here:
https://huggingface.co/transformers/model_doc/mbart.html#mbartforconditionalgeneration

If you get something working, lmk for sure!  I haven't played around enough
with this transformer to get it working with good results ... it works, but
the results don't look great which means I'm doing something wrong :).
Either way, check out the blurr docs and if you get some good results, feel
free to PR an example notebook which I'd be glad to include alongside the
multi-label classification example already in there.

- wg

**Comment by HeroadZ** [comment]
I will take a loot at it.
