### ISSUE TITLE
Issues about summarization part

### ISSUE THREAD

**Issue by HeroadZ** [ohmeow/blurr#27]
Hi, sorry to disturb you again. I have been recently fine-tuning mbart and mt5 with the help of blurr docs.
https://ohmeow.github.io/blurr/modeling-seq2seq-summarization/
https://github.com/ohmeow/ohmeow_website/blob/master/_notebooks/2020-05-23-text-generation-with-blurr.ipynb

But something made me confused.
1. "summarize: " prefix of MT5
in your test code, you add this prefix only for T5, does MT5 also need it or not?
```python
def add_t5_prefix(inp): return f'summarize: {inp}' if (hf_arch == 't5') else inp
```

also I get an error for using your code
```sh
Traceback (most recent call last):
  File "my_blurr.py", line 40, in <module>
    dblock = DataBlock(blocks=blocks, get_x=Pipeline([ColReader('article'), add_t5_prefix]), get_y=ColReader('summary'), splitter=RandomSplitter())
TypeError: __init__() missing 1 required positional argument: 'tokenizer'
```

2. loss function
In the notebook of fine-tuning bart, you use `CrossEntropyLossFlat`, but `HF_PreCalculatedLoss` is used in the test code. Is there any difference between them and which should I use?

3. got an error when generating using fine-tuned mbart
I fine-tuned the mbart only with 100 Japanese samples but still got 0.28 of the rouge score. but when I use the generate function, it got an error.
```
Traceback (most recent call last):
  File "my_blurr.py", line 91, in <module>
    learn.blurr_generate(test_article, early_stopping=True, num_beams=4)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/blurr/modeling/seq2seq/core.py", line 225, in blurr_generate
    input_ids = hf_tokenizer.encode(inp, padding=True, truncation=True, return_tensors='pt', **tok_kwargs)
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2092, in encode
    encoded_inputs = self.encode_plus(
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2408, in encode_plus
    return self._encode_plus(
  File "/home/zchelllo/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 448, in _encode_plus
    batched_output = self._batch_encode_plus(
TypeError: _batch_encode_plus() got an unexpected keyword argument 'src_lang'
```

Is this related to the following code?
```py
tok_kwargs = {}
if (hf_arch == 'mbart'):
    text_gen_kwargs['decoder_start_token_id'] = hf_tokenizer.get_vocab()["ja_XX"]
    tok_kwargs = {"src_lang": "ja_XX", "tgt_lang": "ja_XX"}
```

Sorry if they are stupid questions. Thanks in advance!

**Comment by ohmeow** [comment]
Often, the only stupid the question is the one not asked :)

Actually, good point.  I haven't spent time working with mt5 and mbart
outside of making sure the code runs.  If I get a chance, I'll take a look
this weekend.  Thanks for bringing this up, and if you make any headway,
feel free to add a comment to this thread.

Thanks - Wayde

**Comment by HeroadZ** [comment]
I found that members of transformers have updated the new script for fine-tuning seq2seq model on summarization or translation tasks. Less code and simpler understanding. Wish it be helpful to the improvements of blurr.
https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_seq2seq.py

**Comment by ohmeow** [comment]
I'll take a look.  

In the meantime, can I close this out?  Thanks much!
