### ISSUE TITLE
KeyError: 1

### ISSUE THREAD

**Issue by iamdavie** [ohmeow/blurr#30]
I am getting an error when trying to import on Kaggle

`The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-7-294eeb27ef26> in <module>
      3 from fastai.text.all import *
      4 
----> 5 from blurr.data.all import *
      6 from blurr.modeling.all import *

/opt/conda/lib/python3.7/site-packages/blurr/data/all.py in <module>
----> 1 from ..utils import *
      2 from .core import *
      3 from .question_answering import *
      4 from .token_classification import *
      5 from .seq2seq.core import *

/opt/conda/lib/python3.7/site-packages/blurr/utils.py in <module>
    186 
    187 # Cell
--> 188 BLURR_MODEL_HELPER = ModelHelper()
    189 
    190 # Cell

/opt/conda/lib/python3.7/site-packages/blurr/utils.py in __call__(self, *args, **kwargs)
     25 
     26     def __call__(self, *args, **kwargs):
---> 27         if self._instance == None: self._instance = self._cls(*args, **kwargs)
     28         return self._instance
     29 

/opt/conda/lib/python3.7/site-packages/blurr/utils.py in __init__(self)
     59         model_type_df = self._df[(self._df.functional_area == 'modeling')].class_name.str.split('For', n=1, expand=True)
     60 
---> 61         model_type_df[1] = np.where(model_type_df[1].notnull(),
     62                                     'For' + model_type_df[1].astype(str),
     63                                     model_type_df[1])

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2904             if self.columns.nlevels > 1:
   2905                 return self._getitem_multilevel(key)
-> 2906             indexer = self.columns.get_loc(key)
   2907             if is_integer(indexer):
   2908                 indexer = [indexer]

/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:
-> 2897                 raise KeyError(key) from err
   2898 
   2899         if tolerance is not None:

KeyError: 1`

**Comment by ohmeow** [comment]
What versions of fastai and transformers are you using?  Also, what version of ohmeow-blurr?
