### ISSUE TITLE
Cannot train model on google colab

### ISSUE THREAD

**Issue by iamdavie** [ohmeow/blurr#31]
I switched to using google colab but i run into the following error
`IndexError                                Traceback (most recent call last)

<ipython-input-22-6ff390c95696> in <module>()
----> 1 learn.fit_one_cycle(4, lr_max=1e-3)

20 frames

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   2262                          .format(input.size(0), target.size(0)))
   2263     if dim == 2:
-> 2264         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   2265     elif dim == 4:
   2266         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

IndexError: Target 2 is out of bounds.

`

**Comment by ohmeow** [comment]
Can you share your code via a gist so I can take a look?

Just a guess, but if your doing classification you'll want to make sure you tell your transformer model how many classes (or else for multilabel how many labels) you are predicting.

See [here](https://ohmeow.github.io/blurr/examples-multilabel/) and in particular this code:
```
task = HF_TASKS_ALL.SequenceClassification

pretrained_model_name = "distilroberta-base"
config = AutoConfig.from_pretrained(pretrained_model_name)
config.num_labels = len(lbl_cols)

hf_arch, hf_config, hf_tokenizer, hf_model = BLURR_MODEL_HELPER.get_hf_objects(pretrained_model_name, 
                                                                               task=task, 
                                                                               config=config)
```
