### ISSUE TITLE
Cannot suppress nltk warnings

### ISSUE THREAD

**Issue by leviritchie** [ohmeow/blurr#36]
Normally, when downloading wordnet with nltk, you could suppress the warnings like so:

`nltk.download('wordnet', quiet=True)`

This doesn't work when importing modules, e.g. from blurr.data.all import *. In fact, none of the traditional output suppression techniques seems to work (like running with -W). 

This isn't a big deal in a jupyter notebook, but it can be a pain when running inference as part of an automated job.

**Comment by ohmeow** [comment]
Yah, I've tolerated these warnings too ... sounds like an easy fix.  I'll make this happen in the next release.  Thanks for bringing it up!

**Comment by ohmeow** [comment]
This is fixed now with the 0.0.26 release.
