### ISSUE TITLE
Knowledge Distillation

### ISSUE THREAD

**Issue by Lundez** [ohmeow/blurr#37]
Is there a way to achieve Knowledge Distillation. That is distill knowledge from a HuggingFace trained model to ULMFit (Fast.ai LM)?

**Comment by ohmeow** [comment]
Not that I know of ... you may want to ask on the fastai forums and/or
discord.

**Comment by Lundez** [comment]
Thanks 

I'll research further. Will try to post here, perhaps if I get some really good results with a smooth implementation I'll add a PR too 👍😊

**Comment by ohmeow** [comment]
Thanks.
