### ISSUE TITLE
No module named 'nlp'

### ISSUE THREAD

**Issue by tyoc213** [ohmeow/blurr#4]
I got this when trying to import after installing from master `pip install -e ".[dev]"` I try to use it on a ipynb and got this:

``` python
import torch
from transformers import *
from fastai2.text.all import *

from blurr.data.all import *
from blurr.modeling.all import *
```
I get

```log
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-906f6e0a84bd> in <module>
      3 from fastai2.text.all import *
      4 
----> 5 from blurr.data.all import *
      6 from blurr.modeling.all import *

~/Documentos/github/blurr/blurr/data/all.py in <module>
      1 from ..utils import *
----> 2 from .core import *
      3 from .language_modeling import *
      4 from .question_answering import *
      5 from .token_classification import *

~/Documentos/github/blurr/blurr/data/core.py in <module>
      6 from functools import reduce
      7 
----> 8 import torch, nlp
      9 from transformers import *
     10 from fastai2.text.all import *

ModuleNotFoundError: No module named 'nlp'
```

**Comment by tyoc213** [comment]
Well, it is solved with a `pip install nlp` there is no `conda install nlp` but I guess it should be listed somewhere?

**Comment by ohmeow** [comment]
Yah I'll add `nlp` to the requirements file.

Will have to try `xlm-roberta-base` ... weird that it's causing the notebook to restart itself.

**Comment by tyoc213** [comment]
Yes, the bad thing is that I dont see a traceback or something, only that, do you need more specific specs or something?

**Comment by ohmeow** [comment]
Give me as much info as you can ... GPU(s), running local or colab, etc....  I'll see if I can reproduce.

**Comment by tyoc213** [comment]
Running locally with conda with fastai2 and core installed locally from github repo https://gist.github.com/41b8d0413833fd758f499978ebff38a0

Driver Version: 435.21       CUDA Version: 10.1
GeForce RTX 2080 8Gb
3~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ohmeow** [comment]
The nlp not found issue is fixed in the latest master branch.  If you can, please open a separate issue re: the issues with `xlm-roberta-base`.  Thanks.
