### ISSUE TITLE
Fine tune google/byt5-small

### ISSUE THREAD

**Issue by epetros** [ohmeow/blurr#40]
Greetings,
I tried fine tuning with google/byt5-small, it seemed to work well, but when trying to generate with learn.blurr_generate just outputs gibberish. As a comparison, fine tuning  t5-small with the same data works well both on training and text generation with learn.blurr_generate. 
What could I be missing?
Thanks

**Comment by ohmeow** [comment]
Its not you missing anything :)

I need to adjust the tokenizer to work the the byt5 models.  It's on my list :). Will comment back here once I have something working.

**Comment by epetros** [comment]
Thanks! Looking forward to it.

**Comment by epetros** [comment]
> 
> 
> Its not you missing anything :)
> 
> I need to adjust the tokenizer to work the the byt5 models. It's on my list :). Will comment back here once I have something working.

I wonder if this affects the training process or just the text generation afterwards?

**Comment by epetros** [comment]
Thanks!
