### ISSUE TITLE
QA task preprocessing

### ISSUE THREAD

**Issue by ocm248** [ohmeow/blurr#44]
Hi, 
I use the QA example with `load_dataset('squad_v2', split='train')`. The dataset contains column 'Answer', `pre_process_squad `expects column 'answer_text' which produces a KeyError: 'answer_text'.

That topic was already described [here](https://github.com/ohmeow/blurr/issues/19) and should be fixed. 
What's wrong here?

BTW - great library!

**Comment by ohmeow** [comment]
Give a look at the latest release.  You should be able to pass the column/attribute for question,  context, and answer.

Lmk.

Thanks-wg

**Comment by ocm248** [comment]
The content in column 'answers' is different, e. g. like this: {'text': array(['in the late 1990s'], dtype=object), 'answer_start': array([269], dtype=int32)}. It contains the `answer_text `as well as the start position (start_idx).
To set `tok_answer_start `and `tok_answer_end ` I did the following:
```
def pre_process_squad_(row, hf_arch, hf_tokenizer):
    #context, qst, ans = row['context'], row['question'], row['answer_text']
    context, qst = row['context'], row['question']
    ans = row['answers'].split('[', 1)[1].split(']')[0]

    tok_kwargs = {}

    if(hf_tokenizer.padding_side == 'right'):
        tok_input = hf_tokenizer.convert_ids_to_tokens(hf_tokenizer.encode(qst, context, **tok_kwargs))
    else:
        tok_input = hf_tokenizer.convert_ids_to_tokens(hf_tokenizer.encode(context, qst, **tok_kwargs))
    #tok_ans = hf_tokenizer.tokenize(str(row['answer_text']), **tok_kwargs)  # OM wird ersetzt durch
    tok_ans = hf_tokenizer.tokenize(str(ans), **tok_kwargs)

    start_idx, end_idx = 0,0
    # OM  07/12/21
    try:
      _start_idx = row['answers'].split('[', 1)[1].split('[')[1].split(']')[0]
      start_idx = int(_start_idx) if len(_start_idx)>0 else 0
      end_idx = start_idx + len(ans[1:-1])
    except: pass
    #
    """
    for idx, tok in enumerate(tok_input):
        try:
            if (tok == tok_ans[0] and tok_input[idx:idx + len(tok_ans)] == tok_ans):
                start_idx, end_idx = idx, idx + len(tok_ans)
                break
        except: pass
    """
    #pdb.set_trace()
    row['tokenized_input'] = tok_input
    row['tokenized_input_len'] = len(tok_input)
    row['tok_answer_start'] = start_idx
    row['tok_answer_end'] = end_idx

    return row
```
It seems the data source is not in  very good shape, there are many variations that need to be covered.
Running above code ends up with an error in 
`dls = dblock.dataloaders(squad_df, bs=4)`

>     246             return TensorCategory(self.vocab.o2i[o])
>     247         except KeyError as e:
> --> 248             raise KeyError(f"Label '{o}' was not included in the training dataset") from e
>     249     def decodes(self, o): return Category      (self.vocab    [o])
>     250 
> 
> KeyError: "Label '140' was not included in the training dataset"

Don't know what's the problem here. Could it be not all cases are covered above?

To exclude possible error sources here is the way I prepare my data:
```
dataset = load_dataset('squad_v2', split='train[:5%]')
dataset.to_csv('squad_train.csv')
squad_df = pd.read_csv('./squad_train.csv')
```

**Comment by ohmeow** [comment]
You want to grab the latest version of Blurr ... and then reference this in
the examples for how to preprocess the HF datasets object you are looking
at:

https://ohmeow.github.io/blurr/examples-high-level-api/#Question-Answering

Lmk how it goes.

-wg

**Comment by tgalery** [comment]
thanks for the awesome work, as a follow up to this, I was wondering if we could use fastai models, like aws_lstm with transformer tasks like extractive question answering.

**Comment by ohmeow** [comment]
Sure ... you would have to create a head on top of the LSTM backbone for
the task in the same way you see how fastai replaces the causal LM head
with a classification head.
