### ISSUE TITLE
TypeError: unhashable type: 'slice' in Learner.summary with fastai version 2.5.3

### ISSUE THREAD

**Issue by manisnesan** [ohmeow/blurr#56]
**Reproducer** 
fastai : 2.5.3
transformers : 4.12.2
ohmeow-blurr : 0.1.0

https://gist.github.com/manisnesan/404ec6f61376b5a1f3b6798816ffe311

This is due to the change introduced here. https://github.com/fastai/fastai/pull/3506

**Comment by manisnesan** [comment]
Hi @ohmeow, there is a regression with the recent fastai release 2.5.3

**Comment by ohmeow** [comment]
Looking at this now. Thanks for the heads up

**Comment by ohmeow** [comment]
Yup. Just posted a PR for fastai to fix.  Will close this out if/once its verified.

Thanks - wg

**Comment by ohmeow** [comment]
This looks fixed in latest fastai.  Feel free to reopen if not.
