### ISSUE TITLE
ModuleNotFoundError: No module named 'blurr.data'

### ISSUE THREAD

**Issue by him-singhvi** [ohmeow/blurr#63]
I did following in my notebook,

1. pip install fastbook
2. pip install blurr

3. from fastbook import load_learner
4. from blurr.data.all import *

5. inf_learn = load_learner(fname='fb_solution_big.pkl')

Error
ModuleNotFoundError: No module named 'blurr.data'

**Comment by ohmeow** [comment]
It's `pip install ohmeow-blurr` :)

**Comment by him-singhvi** [comment]
Thanks, it worked :)
