### ISSUE TITLE
Problem in Github README 

### ISSUE THREAD

**Issue by mehulfollytobevice** [ohmeow/blurr#65]
In the last section of the GitHub README, there is a problem with one of the links.
In the **Props** section, the link for  the article [A Tutorial to Fine-Tuning BERT with Fast AI](https://mlexplained.com/2019/05/13/a-tutorial-to-fine-tuning-bert-with-fast-ai/) leads us to a site for electronic products. Please fix it .

![image](https://user-images.githubusercontent.com/49192179/157449961-65cc2962-471c-4b50-b587-b275f2cd9adb.png)

**Comment by ohmeow** [comment]
Fixed in dev. branch. Thanks again.
