### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by him-singhvi** [ohmeow/blurr#66]
1. pip install fastbook
2. pip install ohmeow-blurr

3. from fastbook import load_learner

as soon as I run the line number 3 jupyter kernel dies and show below error 
![image](https://user-images.githubusercontent.com/30286290/158664057-25541c93-773b-4eac-be3f-0c47fdcfe34f.png)

I also tried running import fastbook in python terminal it shows me 
**segmentation fault**

**Comment by ohmeow** [comment]
`load_learner` is defined in fastai library (not fastbook).  Take a look at
the fastai docs for structuring your imports correctly (sometimes it can be
difficult figuring out where everything lives).

-wg

**Comment by him-singhvi** [comment]
but for me on python 3.7 it worked for one server.
![image](https://user-images.githubusercontent.com/30286290/158739772-a539080b-b2b1-4651-8b82-9e1b24e40703.png)

you can see from fastai it throws error but from fastbook it worked fine and loaded the model too.
Is it because of python version. I am using 3.8 at the machine where I am having issue.
Please guide,

**Comment by ohmeow** [comment]
`load_learner` is defined in `fastai.leaner`.

See: https://docs.fast.ai/learner.html#load_learner
