### ISSUE TITLE
Notebook error: "NameError: name 'HF_MODELS' is not defined

### ISSUE THREAD

**Issue by boxabirds** [ohmeow/blurr#7]
I'm running the blurr notebook and hit an error that I'd love some help with:

```
pretrained_model_name = "bart-large-cnn"

hf_arch, hf_tokenizer, hf_config, hf_model = \
    BLURR_MODEL_HELPER.get_hf_objects(pretrained_model_name, BartTokenizer, HF_MODELS.BartForConditionalGeneration)

hf_arch, type(hf_tokenizer), type(hf_config), type(hf_model)
```

Error
```
NameError                                 Traceback (most recent call last)
<ipython-input-8-39f983a4d82d> in <module>()
      1 pretrained_model_name = "bart-large-cnn"
      2 
----> 3 hf_arch, hf_tokenizer, hf_config, hf_model =     BLURR_MODEL_HELPER.get_hf_objects(pretrained_model_name, BartTokenizer, HF_MODELS.BartForConditionalGeneration)
      4 
      5 hf_arch, type(hf_tokenizer), type(hf_config), type(hf_model)

NameError: name 'HF_MODELS' is not defined
```

I spent some time trying to understand the code and find reference to this but I came up short. I'm presuming the notebook is out of date and there's a new way to call `get_hf_objects`?

**Comment by ohmeow** [comment]
You are correct.

See here for an updated example on how to use BART for summarization:  https://ohmeow.github.io/blurr/data-text-generation/

(btw, things will probably be changing a bit here and there until a version 1 ... but I try to keep the docs at least updated for the time being :) )

**Comment by boxabirds** [comment]
Thanks! Yes I saw the warning, no problem at all. Not urgent
