### ISSUE TITLE
Dead? Will vision transformers come? Last commit 2 years ago

### ISSUE THREAD

**Issue by roboserg** [ohmeow/blurr#71]
Dead? Will vision transformers come? Last commit 2 years ago

**Comment by ohmeow** [comment]
Not sure if you're looking at the right repo ... but last commit looks to be around 25 days ago.

I haven't had time to begin introducing ViTs.  Always open to PRs.

**Comment by roboserg** [comment]
Sorry, I must have overlooked. Thanks for the reply.
