### ISSUE TITLE
Fine-Tuning the BART Large Model for Text Summarization NOT RUNNING

### ISSUE THREAD

**Issue by lucawagner1510** [ohmeow/blurr#72]
hello, I tried to run the code written in the article: https://towardsdatascience.com/fine-tuning-the-bart-large-model-for-text-summarization-3c69e4c04582 
 but I think the code is not updated because it does not find for example HF_Seq2SeqBeforeBatchTrans
form and other functions.
Do you have any suggestions?
Many thanks
Luca

**Comment by ohmeow** [comment]
Yup, that's pre-1.0 code.

Your options are:
1. Run the code in that article with a previous version of blurr (e.g., `pip install ohmeow-blurr==0.0.26`)
2. Use the [updated summarization module](https://ohmeow.github.io/blurr/text-modeling-seq2seq-summarization.html) to modify the article's code to work with 1.0

Lmk how it goes.

**Comment by lucawagner1510** [comment]
Thank you very much for your very quick reply: I will do the tests and let you know!

**Comment by ohmeow** [comment]
Feel free to reopen if necessary :)
