### ISSUE TITLE
HF_Seq2SeqBeforeBatchTransform is not defined

### ISSUE THREAD

**Issue by LukasFides** [ohmeow/blurr#73]
Hi, 

I am trying out the provided BART fine tuning script and am facing issues with certain components.

Is there an alternative for the HF_Seq2SeqBeforeBatchTransform? I am currently running into the error:

hf_batch_tfm = HF_Seq2SeqBeforeBatchTransform(hf_arch, hf_config, hf_tokenizer, hf_model, task='summarization',
NameError: name 'HF_Seq2SeqBeforeBatchTransform' is not defined

Any help is highly appreciated.

Cheers,
Lukas

**Comment by ohmeow** [comment]
I think you're referencing this ... https://ohmeow.com/posts/2020/05/23/text-generation-with-blurr.html

I just updated it to use blurr 1.0.x.

If this fixes your issues, please close this out.  Thanks for letting me know it was broken :)
