### ISSUE TITLE
Resuming training

### ISSUE THREAD

**Issue by dimagalat** [ohmeow/blurr#80]
Hello,

I'm trying to implement the following scenarios:
- load a learner to continue training on the same dataset
- load a learner to train on a different dataset

Unfortunately, I get the following error when trying to load a learner:
`runtimeerror: pytorchstreamreader failed reading zip archive: failed finding central directory
`
I've read that [load_learner](https://docs.fast.ai/learner.html#load_learner), "requires all your custom code be in the exact same place as when exporting". Could someone clarify what that means in practice? Re-loading all the same objects in the environment?

Can anyone point out an example where a learner is used on a different dataset?

Thanks in advance, I really appreciate your help

**Comment by dimagalat** [comment]
learn.hf_model.save_pretrained("model")
hf_tokenizer.save_pretrained("model")
solves it

**Comment by ohmeow** [comment]
Ok cool ... yah that makes sense for transformers.  I'll try to find some
time to add this to blurr so a single method gets the job done.

Thanks
